### ISSUE TITLE
Just here to express my excitement.

### ISSUE THREAD

**Issue by nicovanzyl** [mojs/mojs.github.io#1]
And if there's anything I/we can do to help contribute please shout!

![Excited avocado](https://media.giphy.com/media/l2JHRhAtnJSDNJ2py/giphy.gif)

**Comment by xavierfoucrier** [comment]
Hi @nicovanzyl!

Haha thanks for your feedback, @Sandstedt is working hard to make the documentation + tutorials up and running. We also have a lot of things to do before releasing the website.

Stay tuned by starring/watching the repo.
:sunglasses:
