### ISSUE TITLE
Maybe example with react hooks

### ISSUE THREAD

**Issue by cctoni** [mojs/mojs.github.io#14]
Was somebody able to make this thing work with react and functional components? Would be great if somebody could share some ideas.

**Comment by Sandstedt** [comment]
@cctoni I guess you found a solution already, but here's an example how I use MoJS with hooks in React:
https://codesandbox.io/s/mojs-react-example-kbikb?file=/src/MojsExample.js

I will also do a short post on the site later and post here.
