### ISSUE TITLE
Fix dead links in API section

### ISSUE THREAD

**Issue by Sandstedt** [mojs/mojs.github.io#19]
Ex at https://mojs.github.io/api/burst/ - link ShapeSwirl API goes to https://mojs.github.io/api/shape-swirl.html. Should go to https://mojs.github.io/api/shape-swirl/

Please add more dead links in comments below.

**Comment by xavierfoucrier** [comment]
Thanks for opening this issue!
Didn't notice this on the docs website.

We should fix this before releasing the v1.
