### ISSUE TITLE
Use the latest org. scoped package

### ISSUE THREAD

**Issue by xavierfoucrier** [mojs/mojs.github.io#2]
Update the documentation to **use the latest organization scoped package** `@mojs/core` instead of the old `mo-js` package name.

**Comment by Sandstedt** [comment]
This is fixed everywhere already. Did I miss it somewhere?

**Comment by xavierfoucrier** [comment]
Haha no @Sandstedt :smile:,

I just assign you because you were working on it.
Closing the issue :v:
