### ISSUE TITLE
Problem controlling Mojs Curve Editor

### ISSUE THREAD

**Issue by B3ns44d** [mojs/mojs.github.io#21]
When I click ***Open Demo** Majos Curve editor It does not open completely, Sidebar affects its full appearance

### video 
![screencast-mojs github io-2021 02 09-22_03_32](https://user-images.githubusercontent.com/43497143/107494402-a7352600-6b86-11eb-82b1-364c1cc8ca09.gif)

**Comment by xavierfoucrier** [comment]
Hi @B3ns44d,

Good catch :bug:
 
As we are not able to define the mojs curve editor position when initializing it, I suggest to adjust the `z-index` position in the website layout. I put @Sandstedt in copy of this issue in order for him to have a look at this as soon as possible.

Thanks again! :wink:

**Comment by B3ns44d** [comment]
The sidebar affects it, causing it not to appear above it, but the editor can be made to open in the middle of the screen using 
```css
style="transform: translate (50%, 50%); width: 980px; height: 475px;"
```
It's a temporary solution

**Comment by xavierfoucrier** [comment]
We will look into it shortly :wink:
