### ISSUE TITLE
Translate documentation to Chinese

### ISSUE THREAD

**Issue by mengguagua** [mojs/mojs.github.io#29]
If not, can I translate a Chinese website for Chinese people to learn? It won't infringe, will it?

**Comment by xavierfoucrier** [comment]
Hello @mengguagua,

I just transferred your issue in the appropriate repository.
Unfortunately we don't have a Chinese version of the mojs website.

It's a great idea, but I am seeing possible issues when translating:
- we need to review what you are translating and how you are translating it
- we are not speaking Chinese
- we need to care about having same content synced between both versions
- being only one to translate the website will require a lot of efforts

For me this job require a dedicated team of people, speaking both well English and Chinese and support the whole documentation site to be up to date every time in both way.

@Sandstedt what do you think about that?

**Comment by Sandstedt** [comment]
@mengguagua @xavierfoucrier VuePress that we are using to build the documentation site has build-in support for localisation. So technically there should be no problem (https://vuepress.vuejs.org/guide/i18n.html#site-level-i18n-config).

But translating is not an easy task, especially not on this large documentation. And it also doubles the amount of work when changing things to also translate it afterwards. Secondly I need to be able to give that responsibility to a person I can trust. So what I do is to check the translators GitHub profile and other online activity to try to get a picture of this person (in this case you). And seeing no prior contribution or activity on GitHub, no real profile picture, no link to a personal website or other social media, directly gives me a red flag, I'm sorry. Nothing personal. You're probably a great translator and it's a good start to get into contributing to the Open Source world. But in the open source world, you also need to put security first.

But I do agree that having the docs translated in as many languages as possible is a great idea in theory, but giving we are a such small team that does not work on this project full-time, it's also very hard for us to maintain.

**Comment by xavierfoucrier** [comment]
I totally agree with you @Sandstedt for everything said.
Closing the issue.

**Comment by elarbor** [comment]
+1
我也希望能加入中文的官网。可以使用 i18n 技术实现
